Layout/LineLength:
  AutoCorrect: true
  Max: 100

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$client]
