version: 2.1
orbs:
  ruby: circleci/ruby@1.1.3

jobs:
  github:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          command: |
            cd ./metrics_automation/github
            bundle install
            bundle exec rubocop
  jenkins:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          command: |
            cd ./metrics_automation/jenkins
            bundle install
            bundle exec rubocop

workflows:
  version: 2
  github_and_jenkins:
    jobs:
      - github
      - jenkins
